development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  pool:5
  database: fierce-bayou-9638_production
  username: fierce-bayou-9638_production
  password: <%= ENV['fierce-bayou-9638_DATABASE_PASSWORD'] %>
